[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview -- --host 0.0.0.0 --port $PORT'

[variables]
NODE_ENV = 'production'